// import './globals.css'
import { ReactNode } from "react";
import "../assets/styles/main.scss";

import HeaderMain from "@/components/headerMain";
import FooterMain from "@/components/footerMain";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

interface IProps {
  children: ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="pt-BR">
      <body>
        <HeaderMain />
        <main>{children}</main>
        <FooterMain />
      </body>
    </html>
  );
}
